services:
  web:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    working_dir: /app/vulnerable_app
    user: "1000:1000"
    command: python manage.py runserver 0.0.0.0:8000
